# Generated by Django 6.0.1 on 2026-02-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
